version: "3.9"

services:

  cache:
    container_name: cache
    image: redis:alpine
    volumes:
      - ./trias-extractor/data:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]

  trias-extractor:
    container_name: trias-extractor
    image: ghcr.io/ride2rail/trias-extractor
    build:
      context: ./trias-extractor/
      dockerfile: Dockerfile.production
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  geolocation-fc:
    container_name: geolocation-fc
    image: ghcr.io/ride2rail/geolocation-fc
    build: ./geolocation-fc/
    environment:
      FLASK_ENV: development

  oc-core:
    container_name: oc-core
    image: ghcr.io/ride2rail/oc-core
    build: ./oc-core/oc-core/
    environment:
      FLASK_ENV: development
    depends_on:
      - cache
    links:
      - active-fc
      - environmental-fc
      - panoramic-fc
      - position-fc
      - price-fc
      - time-fc
      - traffic-fc
      - tsp-fc
      - weather-fc
  
  time-fc:
    container_name: time-fc
    image: ghcr.io/ride2rail/time-fc
    build: ./oc-core/time-fc/
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  weather-fc:
    container_name: weather-fc
    image: ghcr.io/ride2rail/weather-fc
    build: ./oc-core/weather-fc
    environment:
      FLASK_ENV: production

  owm_proxy:
    container_name: owm_proxy
    image: ghcr.io/ride2rail/owm_proxy
    build: ./oc-core/weather-fc/owm_proxy
    environment:
      FLASK_ENV: production
    depends_on:
      - weather-fc

  price-fc:
    container_name: price-fc
    image: ghcr.io/ride2rail/price-fc
    build: ./oc-core/price-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  traffic-fc:
    container_name: traffic-fc
    image: ghcr.io/ride2rail/traffic-fc
    build: ./oc-core/traffic-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  environmental-fc:
    container_name: environmental-fc
    image: ghcr.io/ride2rail/environmental-fc
    build: ./oc-core/environmental-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  position-fc:
    container_name: position-fc
    image: ghcr.io/ride2rail/position-fc
    build: ./oc-core/position-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  active-fc:
    container_name: active-fc
    image: ghcr.io/ride2rail/active-fc
    build: ./oc-core/active-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  tsp-fc:
    container_name: tsp-fc
    image: ghcr.io/ride2rail/tsp-fc
    build: ./oc-core/tsp-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  panoramic-fc:
    container_name: panoramic-fc
    image: ghcr.io/ride2rail/panoramic-fc
    build: ./oc-core/panoramic-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  incentive-provider:
    container_name: incentive-provider
    image: ghcr.io/ride2rail/incentive-provider
    build: ./incentive-provider/
    environment:
      FLASK_ENV: production
  
  data-provider:
    container_name: data-provider
    image: ghcr.io/ride2rail/data-provider
    build: ./data-provider/
    environment:
      FLASK_ENV: production
  
  thor-wrapper:
    container_name: thor-wrapper
    image: ghcr.io/ride2rail/thor-wrapper
    build: ./thor-wrapper/
    environment:
      FLASK_ENV: development

  orchestrator:
    container_name: orchestrator
    image: ghcr.io/ride2rail/orchestrator
    build: .
    environment:
      FLASK_ENV: development
    volumes:
      - ./orchestrator.py:/code/orchestrator.py
      - ./orchestrator.conf:/code/orchestrator.conf
    ports:
      - 5000:5000
    depends_on:
      - cache
    links:
      - cache
      - trias-extractor
      - geolocation-fc
      - incentive-provider
      - data-provider
      - thor-wrapper
      - oc-core
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
        com.docker.network.driver.mtu: 1450
